### ISSUE TITLE
ASIHTTPRequest should be replaced

### ISSUE THREAD

**Issue by aaronbrethorst** [gimenete/iOS-boilerplate#10]
Ben Copsey has discontinued it. http://allseeing-i.com/[request_release];

(you'll need to copy and paste the url, at least in safari. make sure you grab the trailing semicolon, too)

**Comment by markrickert** [comment]
Just because the original developer has stopped working on it doesn't mean that all hope is lost. That's the beauty of open source software!

**Comment by gimenete** [comment]
I have seen it. I'm planning to replace ASIHTTPRequest with AFNetworking. Not only because the original developer has stopped to work in the code, but also because AFNetworking seems faster and with great potential. What do you think?

Thanks for the comments!

**Comment by markrickert** [comment]
I'll take a look at AFNetworking... I've never used it and use ASI very heavily in a lot of my projects. If it can handle POSTs, file downloads to the filesystem, and block callbacks, I may look at porting over some of my projects.

**Comment by gimenete** [comment]
Hi, I have replaced ASIHTTPRequest by AFNetworking. This is a major change. See the source and the web site for mor infromation
http://iosboilerplate.com/

Thanks for the suggestion!
