### ISSUE TITLE
libZ absolute version results in "library not found"

### ISSUE THREAD

**Issue by carlwolff** [gimenete/iOS-boilerplate#14]
Patched to non-version specific file.
https://gist.github.com/1292325

**Comment by ahmet** [comment]
I've applied your patch and made a pull request :)

gimenete/iOS-boilerplate#15

Thanks for pointing it out.

**Comment by gimenete** [comment]
Thanks a lot to both of you. I've been on vacances so I couldn't fix it before :)

Nevertheless this dependency is due to ASIHTTPRequest and I'm going to remove it in benefit of AFNetworking. Anyway, thanks a lot!
