### ISSUE TITLE
Swipeable cell gives errors when trying to run the project on device

### ISSUE THREAD

**Issue by sarperdag** [gimenete/iOS-boilerplate#3]
The demo runs perfectly on the simulator but gives weird errors when trying to run on device.

/Users/sarperdag/dev/iphone/iOS-boilerplate/IOSBoilerplate/SwipeableCell.m:28: error: 'backView' undeclared (first use in this function)

/Users/sarperdag/dev/iphone/iOS-boilerplate/IOSBoilerplate/SwipeableCell.m:92: error: 'contentView' undeclared (first use in this function)

**Comment by hanonno** [comment]
I have the same issue, but for me it's not working in the simulator either

**Comment by MdBee** [comment]
Adding "NSDictionary\* info;" to SwipeableCell.h like this solved the problem for me:

@interface SwipeableCell : FastCell {

BOOL swipe;

NSDictionary\* info;

}

**Comment by gimenete** [comment]
It is fixed in the latest commit. Thanks for reporting!
