### ISSUE TITLE
Mixing Model and Controller responsabilities?

### ISSUE THREAD

**Issue by JaviSoto** [gimenete/iOS-boilerplate#5]
First off I should say (again :-) ) that I really love this project, and although I knew most of the libraries you're including, it's really helpful that you're creating some handy methods and classes to achieve tasks that we have to do everywhere :)

I only wanted to comment my concern with some decisions and discuss what you (and other developers) think about it.
I looked through all the clases, and I mostly like how code is organized, except for one thing!

BaseViewController has some methods to do async HTTP requests. This is useful, as you can use this as a base class for a View Controller which has a table and gets the data to fill the table off the network; but this is completely against the MVC paradigm! This puts some Model responsabilites within the Controller (therefore this would be hard to test among other things).
What I suggest, is to take _exactly the same code_ you have to do those requests, and put it in another class (say HTTPRequestHelper or something like that), and inject that class into the BaseViewController during initialization. You could have a default init method which instantiates an object of that class by default, and another init method to pass a different object (probably a subclass of the first, so you make sure it responds to the same methods). Perhaps omething like this:

```
- (id)init {
   return [self initWithHTTPRequestHelper:[[[HTTPRequestHelper alloc] init] autorelease]];
}

- (id)initWithHTTPRequestHelper:(HTTPRequestHelper *)rh {
     if ((self = [super init])) {
        self.requestHelper = rh;  
    }

    return self;
}
```

(please, take this as constructive criticism and not like I'm trying to say you did a bad job!)

**Comment by JaviSoto** [comment]
BTW! If you agree on this, I would love to fork the project and do these changes myself ;)
Tell me what you think :D

Oh, and forgive me that I wrote that in English. There are some international developers following the project and wanted everyone to understand :)

**Comment by gimenete** [comment]
I prefer simplicity. For me it's ok a BaseViewController providing some useful methods for "controlling" things. I don't think it breaks the MVC pattern.

Your idea is great. It remembers me the philosophy of Spring Framework. However I just prefer less code. And nevertheless IOS Boilerplate is not intended to be a framework, but a code base to be modified and extended to fit your needs and preferences.

**Comment by gimenete** [comment]
BTW thanks for commenting and making suggestions! :)

**Comment by JaviSoto** [comment]
I agree with you. My idea is basically dependency injection, it's nothing so fancy xD And it would only make sense if you're actually thinking about testing your application mocking the access to the network, which probably someone who uses that class for simplicity, will not be thinking about...
Anyway I'll keep looking at the Boilerplate progress and will try to help in any way I can :) I hope I can put some of my spare time in adding some cool stuff I have been finding since I started iOS'ing ;)
Good job and good luck!

**Comment by gimenete** [comment]
Thank you very much Javi. I would appreciate any contribution :)
