### ISSUE TITLE
ASIAuthenticationDialog.m @synthesize

### ISSUE THREAD

**Issue by andredublin** [gimenete/iOS-boilerplate#6]
In ASIAuthenticationDialog.m file, starting at line 482, wouldn't it be better to call the @synthesize on a single line?

**Comment by gimenete** [comment]
That source file belongs to ASIHTTPRequest. So you should make your suggestion to them:
http://allseeing-i.com/ASIHTTPRequest/

iOS Boilerplate includes this library. But I haven't worked its source code.
